### ISSUE TITLE
Upgrade to Flutter 3

### ISSUE THREAD

**Issue by user97116** [Dn-a/flutter_tags#92]

**Comment by 1AhmedYasser** [comment]
I Added a pull request but until its merged you can use this

```
flutter_tags:
    git:
      url: https://github.com/1AhmedYasser/flutter_tags
      ref: null-safety
```
